[workspace]
members = ["partial_this", "partial_this_macro"]
resolver = "3"

[workspace.package]
authors = ["2A5F"]
description = "Type-safe partial construction"
edition = "2024"
keywords = ["ctor", "partial", "constructor"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/2A5F/partial_this"
version = "0.5.1"

[workspace.dependencies]
partial_this = {path = "partial_this", version = "0.5.1"}
partial_this_macro = {path = "partial_this_macro", version = "0.5.1"}
proc-macro2 = "1"
quote = "1"
syn = {version = "3", features = ["full"]}
typenum = "1.20"
