[package]
categories = ["rust-patterns", "no-std"]
name = "partial_this"

authors = {workspace = true}
description = {workspace = true}
edition = {workspace = true}
keywords = {workspace = true}
license = {workspace = true}
readme = {workspace = true}
repository = {workspace = true}
version = {workspace = true}

[dependencies]
partial_this_macro = {workspace = true}
typenum = {workspace = true}
